### ISSUE TITLE
looper 崩溃

### ISSUE THREAD

**Issue by ALuoBo** [zhuhuitao/printer#3]
Process: com.huitao.printerdemo, PID: 4385
    java.lang.IllegalStateException: Could not execute method for android:onClick
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:414)
        at android.view.View.performClick(View.java:6603)
        at android.view.View.performClickInternal(View.java:6576)
        at android.view.View.access$3100(View.java:780)
        at android.view.View$PerformClick.run(View.java:26069)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6702)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911)
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Method.invoke(Native Method)
        at androidx.appcompat.app.AppCompatViewInflater$DeclaredOnClickListener.onClick(AppCompatViewInflater.java:409)
        at android.view.View.performClick(View.java:6603) 
        at android.view.View.performClickInternal(View.java:6576) 
        at android.view.View.access$3100(View.java:780) 
        at android.view.View$PerformClick.run(View.java:26069) 
        at android.os.Handler.handleCallback(Handler.java:873) 
        at android.os.Handler.dispatchMessage(Handler.java:99) 
        at android.os.Looper.loop(Looper.java:193) 
        at android.app.ActivityThread.main(ActivityThread.java:6702) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:911) 
     Caused by: java.lang.RuntimeException: Only one Looper may be created per thread
        at android.os.Looper.prepare(Looper.java:103)
        at android.os.Looper.prepare(Looper.java:98)
        at com.huitao.printer.service.PrinterService$MyBinder.onDiscovery(PrinterService.kt:168)
        at com.huitao.printer.PrinterModel.getBondDeviceList(PrinterModel.kt:41)
        at com.huitao.printer.Printer.getBondDevicesList(Printer.kt:45)
        at com.huitao.printerdemo.printer.PrinterActivity.obtainBondDevices(PrinterActivity.kt:66)

**Comment by zhuhuitao** [comment]
看原因是looper导致，就是有多次调用Looper.prepare()导致，您是否有改动代码呢？

**Comment by ALuoBo** [comment]
现在您这边可以正常打印了么？还是崩溃和点测试不能打印两个问题都存在呢？

> 看原因是looper导致，就是有多次调用Looper.prepare()导致，您是否有改动代码呢？

未改动，崩溃出现在多次点击打印之后，应用切换至后台，然后返回应用
